version: 1.0.0-{build}

image: Visual Studio 2022

branches:
  only:
    - main

environment:
  matrix:
    - nodejs_version: 20

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: choco install python --version=3.11.9 -y
  - ps: $env:PYTHON = 'C:\Python311\python.exe'
  - ps: $env:npm_config_python = 'C:\Python311\python.exe'
  - ps: python --version
  - npm ci

build: off

build_script:
  - npx electron-builder --win --x64 --ia32

artifacts:
  - path: dist_electron\**
    name: windows-build
